"""Snapshot equivalence test.

The snapshot fixture (``ops_snapshot.parquet``) is generated by
``scripts/gen_ops_snapshot.py`` against the pandas oracle (it sets
``STOCKPOOL_USE_PYTHON_OPS=1``). Every registered factor's Rust-or-pandas
output is diffed against that oracle.

Default tolerance: ``atol=1e-9, rtol=1e-7`` (per design spec
``docs/superpowers/specs/2026-06-20-rust-ops-acceleration-design.md``).

**Known Rust-vs-pandas ULP divergences** are listed in
``EXPECTED_RUST_DIVERGENCE``. Each entry caps both the per-element drift
**and** the mismatch count, so any further Rust regression — either more
elements drifting, or existing ones drifting more — still breaks the test.
The entries reflect drift observed after Rust ports of ``ts_std`` /
``correlation`` / ``ts_rank`` landed (see commits on ``feat/rust-ops``).
"""
from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from stockpool.factors import list_factors, make_factor
from stockpool.factors.context import set_sector_map
from stockpool.industry_map import load_or_build_industry_map

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests" / "fixtures"
PANEL_PATH = FIXTURES / "ops_panel.parquet"
SNAPSHOT_PATH = FIXTURES / "ops_snapshot.parquet"

# Allowlist of ULP-level Rust divergences from pandas oracle. Caps are
# ~2× the currently observed worst case so noise stays inside the cap
# but any genuine regression escapes. ``alpha_021`` outputs a 3-state
# signal {-1, 0, +1}; tiny numerical drift can flip a sign, hence atol=2.
EXPECTED_RUST_DIVERGENCE: dict[str, dict[str, float]] = {
    "alpha_021": {"atol": 2.0, "rtol": 0.0, "max_mismatches": 10},
    "alpha_022": {"atol": 0.05, "rtol": 0.5, "max_mismatches": 30},
    "alpha_034": {"atol": 0.05, "rtol": 0.05, "max_mismatches": 80},
    "alpha_040": {"atol": 0.02, "rtol": 0.5, "max_mismatches": 150},
    # PR-T1.2: decay_linear dispatcher (Rust +=  vs pandas np.dot  differ by
    # 1 ULP = 2.2e-16). When ts_rank output (exact rationals k/19) goes through
    # decay_linear then ts_rank again, those 1-ULP diffs can flip rank order by
    # exactly 1/19 ≈ 0.0526 per cell. Observed: 15 cells / max_diff = 0.0526.
    "alpha_076": {"atol": 0.06, "rtol": 0.5, "max_mismatches": 30},
}

_STRICT_ATOL = 1e-9
_STRICT_RTOL = 1e-7


def _load_panel() -> dict[str, pd.DataFrame]:
    """Reconstruct a panel dict from the long-form fixture parquet."""
    long = pd.read_parquet(PANEL_PATH)
    long["date"] = pd.to_datetime(long["date"])
    panel: dict[str, pd.DataFrame] = {}
    for field in ("open", "high", "low", "close", "volume"):
        wide = long.pivot(index="date", columns="code", values=field).sort_index()
        wide.index.name = "date"
        wide.columns.name = "code"
        panel[field] = wide
    return panel


@pytest.fixture(scope="module")
def panel() -> Iterator[dict[str, pd.DataFrame]]:
    if not PANEL_PATH.exists():
        pytest.skip(f"{PANEL_PATH} missing — run scripts/gen_ops_snapshot.py")
    # indneutralize-using factors need sector_map; load it once.
    sector_map = load_or_build_industry_map(ROOT / "data", source="auto")
    set_sector_map(sector_map or {})
    yield _load_panel()
    # Reset global sector_map so this test doesn't pollute later tests.
    set_sector_map({})


@pytest.fixture(scope="module")
def expected() -> dict[str, pd.Series]:
    """{factor_name: Series indexed by (date, code) → value}"""
    if not SNAPSHOT_PATH.exists():
        pytest.skip(f"{SNAPSHOT_PATH} missing — run scripts/gen_ops_snapshot.py")
    long = pd.read_parquet(SNAPSHOT_PATH)
    long["date"] = pd.to_datetime(long["date"])
    long = long.set_index(["factor", "date", "code"])["value"]
    return {
        name: long.loc[name]
        for name in long.index.get_level_values(0).unique()
    }


def _mismatch_mask(a: np.ndarray, e: np.ndarray, atol: float, rtol: float) -> np.ndarray:
    """Element-wise mismatch under ``allclose`` semantics with NaN-equal."""
    a_nan, e_nan = np.isnan(a), np.isnan(e)
    nan_mismatch = a_nan ^ e_nan
    both_nan = a_nan & e_nan
    a_filled = np.where(both_nan, 0.0, np.nan_to_num(a))
    e_filled = np.where(both_nan, 0.0, np.nan_to_num(e))
    abs_diff = np.abs(a_filled - e_filled)
    tol = atol + rtol * np.abs(e_filled)
    return nan_mismatch | (~both_nan & (abs_diff > tol))


@pytest.mark.parametrize("factor_name", list_factors())
def test_factor_matches_snapshot(
    factor_name: str,
    panel: dict[str, pd.DataFrame],
    expected: dict[str, pd.Series],
) -> None:
    if factor_name not in expected:
        pytest.skip(f"factor {factor_name} not in snapshot — regenerate fixture")
    f = make_factor(factor_name)
    wide = f.compute(panel)
    actual_long = wide.stack(dropna=False)
    exp = expected[factor_name]
    # Align actual to the snapshot's (date, code) index ordering
    actual = actual_long.reorder_levels(["date", "code"]).reindex(exp.index)

    a = np.asarray(actual.values, dtype=float)
    e = np.asarray(exp.values, dtype=float)

    if factor_name not in EXPECTED_RUST_DIVERGENCE:
        np.testing.assert_allclose(
            a, e, atol=_STRICT_ATOL, rtol=_STRICT_RTOL, equal_nan=True,
            err_msg=f"factor {factor_name} diverged from snapshot",
        )
        return

    # Allowlisted: bound both mismatch count and per-element drift.
    cap = EXPECTED_RUST_DIVERGENCE[factor_name]
    strict_miss = _mismatch_mask(a, e, _STRICT_ATOL, _STRICT_RTOL)
    n_miss = int(strict_miss.sum())
    assert n_miss <= cap["max_mismatches"], (
        f"factor {factor_name}: {n_miss} elements diverge from oracle, "
        f"exceeds allowlist cap {cap['max_mismatches']} — Rust ops may "
        f"have regressed; investigate before bumping the cap."
    )
    if n_miss == 0:
        return
    loose_miss = _mismatch_mask(a, e, cap["atol"], cap["rtol"])
    over = int(loose_miss.sum())
    if over > 0:
        abs_diff = np.abs(np.nan_to_num(a) - np.nan_to_num(e))
        worst = float(abs_diff[loose_miss].max())
        pytest.fail(
            f"factor {factor_name}: {over} element(s) exceed allowlist "
            f"tolerance (atol={cap['atol']}, rtol={cap['rtol']}); worst "
            f"|Δ|={worst:g} — Rust ops drifted further than allowlist."
        )
