"""Continuous-valued factor library for ML-based factor combination.

A ``Factor`` consumes a Panel (``Mapping[str, pd.DataFrame]`` of OHLCV wide frames,
T × N) and returns a T × N ``pd.DataFrame`` of factor values aligned to
``panel['close']``. Factors are look-ahead-safe by construction (row ``i`` may
only depend on rows ``[:i+1]``) so they can be used in walk-forward backtests.

Adding a new factor:

    from stockpool.factors import Factor, register

    @register(
        "my_factor",
        sources=("custom",),
        types=("momentum", "time_series"),
        description="说明一句话",
    )
    class MyFactor(Factor):
        @property
        def name(self) -> str:
            return "my_factor"

        def compute(self, panel):
            return panel["close"].pct_change(10, fill_method=None)

Built-in factors are auto-registered when this package is imported.
"""
from stockpool.factors.base import Factor
from stockpool.factors.registry import (
    FactorSpec,
    all_sources,
    all_types,
    filter_specs,
    get_spec,
    list_factors,
    list_specs,
    make_factor,
    register,
)

# Side-effect: register built-in factors.
from stockpool.factors import technical  # noqa: F401
from stockpool.factors import wq101  # noqa: F401

# WQ101 A-share-localized variants (Phase 2 of WQ101 localization plan).
# Generated by scripts/generate_wq101_variants.py from a factor_analysis
# baseline; absent before Phase 3 runs. Wrap import to keep stockpool
# importable when the generated file doesn't exist.
try:
    from stockpool.factors import wq101_variants as _wq101_variants  # noqa: F401
except ImportError:
    pass

from stockpool.factors import custom  # noqa: F401
from stockpool.factors import original_stats  # noqa: F401
from stockpool.factors import ewma  # noqa: F401
from stockpool.factors import vwap_deviation  # noqa: F401
from stockpool.factors import close_position  # noqa: F401
from stockpool.factors import turnover_extra  # noqa: F401
from stockpool.factors import acceleration  # noqa: F401
from stockpool.factors import single_stock_vol  # noqa: F401
from stockpool.factors import composite  # noqa: F401
from stockpool.factors import rank_correlation  # noqa: F401
from stockpool.factors import cross_sec_breadth  # noqa: F401
from stockpool.factors import fundamentals  # noqa: F401
from stockpool.factors import gtja191  # noqa: F401

__all__ = [
    "Factor",
    "FactorSpec",
    "register",
    "make_factor",
    "list_factors",
    "list_specs",
    "get_spec",
    "filter_specs",
    "all_sources",
    "all_types",
]
